### PR TITLE
fixed the issue of the game not starting

### PR DESCRIPTION
**Pull request by geamnegru**

### CODE REVIEW

**Comment by geamnegru** [comment]
@hiranmay1000

**Comment by geamnegru** [comment]
i made this PR 14 days ago and it isnt merged

**Comment by hiranmay1000** [comment]
Done@Gamsti1337 ...🦸

**Comment by hiranmay1000** [comment]
Thanks a lot man @Gamsti1337. Now it's working properly, I appreciate ❤️.

**Comment by geamnegru** [comment]
nice

**Pull request merged**
