### PR TITLE
#3 fixed

### PR DESCRIPTION
**Pull request by geamnegru**
check issue thread for explanation

### CODE REVIEW

**Comment by hiranmay1000** [comment]
Thank you @Gamsti1337. One more issue is there. If you play the game for several times, then you find the issue.

**Comment by geamnegru** [comment]
@hiranmay1000 opened the console and didn't find anything

**Comment by hiranmay1000** [comment]
Okay buddy.....@Gamsti1337

**Comment by geamnegru** [comment]
I have been reading the blackjack.js file and I found a probable bug.

On the function newCard we check if isAlive is true and hasBlackjack is false. After that it assigns the function getRandomcard and then pushes it into an empty array (cards), then it adds newCard to sum and then it renders the game.

After my tests, I've seen that "play the game for several times" means just getting blackjacked. When you get blackjacked isAlive is set to false and blackjack is set to false too.

Now getting back to the newCard function we see that the if check has the AND operator that with isAlive being false and blackjack being false too (while the if checks isAlive is true and if blackjack is false) this will not execute the code inside the if, that resulting in the game not working.

Working on it!

**Pull request merged**
